### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by iquykumo** [LovelyCatHyt/CProjects#4]
Good night Right Honourable Dalao!
It is my pleasure to clone and study your program.
Nevertheless, it is unfortunate that there are some problems in my use.

1. On account of my default color of console is not the white characters with black background. This results that it displays abnormally. I sincerely hope you can initialize the color of console. 
2. When I exit the program, it  displays a garbled code, I believe you can fix the bug.

Sincerely,
A Mengxin from ZuojialongCambridgeUniversity

**Comment by LovelyCatHyt** [comment]
Thanks for your feedback!
For problem 1:I thought everyone use a blackbackground console until I saw your issue.. I will fix it soon.
For problem 2:Compile again with args followed:"-fexec-charset=GBK -finput-charset=UTF-8" so that the Chinese characters are encoded currectly.

**Comment by j1g5awi** [comment]
So，why you two Chinese talk in English？

**Comment by iquykumo** [comment]
> So，why you two Chinese talk in English？

// Tactical English
This can give people a sense of professionalism. // manual funny.

**Comment by LovelyCatHyt** [comment]
Well, as Litan-2000 opened this issue in English, I have no reason not using Eng :)

**Comment by LovelyCatHyt** [comment]
You can set the default console color now!
